### ISSUE TITLE
Is there a provision for going back to previous step?

### ISSUE THREAD

**Issue by ArunPandiyan** [drozdzynski/Steppers#4]
First of all, this is a great library. Congrats on that. I wonder, is there any provision for going back to previous steps?

**Comment by drozdzynski** [comment]
If you want that functionality I must code it :smile: and add next button into layout

**Comment by ArunPandiyan** [comment]
But that Previous button completes the idea of this library. It would be great if you do that. Thanks!

**Comment by MikoBlaiz** [comment]
I agree. It would be great.

**Comment by Sehalsein** [comment]
Hi, In the SteppersAdapter.java file add the below code

```
    private void previousStep() {
        if(this.currentStep > 0){
            this.removeStep = currentStep;
            this.beforeStep = currentStep;
            this.currentStep = this.currentStep - 1;
            Log.e("Library", "remove : "+removeStep+" before : "+beforeStep + "cureent  : "+ currentStep);
            notifyItemRangeChanged(removeStep, currentStep);
            notifyItemChanged(currentStep);
        } else Toast.makeText(context,"Cant go back on this one", Toast.LENGTH_SHORT).show();
   }

```

And change this method

```
if(config.getOnCancelAction() != null)
            holder.buttonCancel.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {

                    config.getOnCancelAction().onCancel();
                    previousStep();

                }
            });
```

**Comment by ArunPandiyan** [comment]
I'll put that code in my project. Anyway thanks man!

**Comment by drozdzynski** [comment]
@Sehalsein can you make Pull Request?

**Comment by JulienRaad** [comment]
Hello guys, 

There is no need to check if current position > 0, However you should add in the the bindViewHolder method another condition because there is no need to show the previous button if we are in the first step

`  if (position == 0) holder.buttonCancel.setVisibility(View.GONE);`

The previousStep() method should now then be like this: (Note that notifyItemRangeChanged(removeStep, 1) is the right one AND NOT notifyItemRangeChanged(removeStep, currentStep) )

` private void previousStep() {

            this.removeStep = currentStep;
            this.beforeStep = currentStep;
            this.currentStep = this.currentStep - 1;
            Log.e("Library", "remove : "+removeStep+" before : "+beforeStep + "current  : "+ currentStep);
            notifyItemRangeChanged(removeStep, 1);
            notifyItemChanged(currentStep);

    }`

Finally, we might also change the text of the cancel button to "Previous" instead of "Cancel"

**Comment by JulienRaad** [comment]
Hello guys,

There is no need to check if current position > 0, However you should add in the the bindViewHolder method another condition because there is no need to show the previous button if we are in the first step

`if (position == 0) holder.buttonCancel.setVisibility(View.GONE);`

The previousStep() method should now then be like this: (Note that the method   notifyItemRangeChanged(removeStep, 1) is the right one AND NOT notifyItemRangeChanged(removeStep, currentStep) )

` private void previousStep() {

```
    this.removeStep = currentStep;
    this.beforeStep = currentStep;
    this.currentStep = this.currentStep - 1;
    Log.e("Library", "remove : "+removeStep+" before : "+beforeStep + "current  : "+ currentStep);
    notifyItemRangeChanged(removeStep, 1);
    notifyItemChanged(currentStep);
```

}`
Finally, we might also change the text of the cancel button to "Previous" instead of "Cancel".
